// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL0ceE_hJeAasMptxtlTqkXt6BYRVoyLU',
    appId: '1:590788169175:android:ea9e16fb89fe9dc6d80f92',
    messagingSenderId: '590788169175',
    projectId: 'qarshibotanicalgardens-927c3',
    storageBucket: 'qarshibotanicalgardens-927c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxYRevFpXzf7x_gHZxYQ0MW4_ruxLb5lQ',
    appId: '1:590788169175:ios:5df39c46b1f0c3e4d80f92',
    messagingSenderId: '590788169175',
    projectId: 'qarshibotanicalgardens-927c3',
    storageBucket: 'qarshibotanicalgardens-927c3.appspot.com',
    iosClientId:
        '590788169175-552g6r2m6147fvodajocjtu9fpm5t6i8.apps.googleusercontent.com',
    iosBundleId: 'com.example.qarshiApp',
  );
}
